apiVersion: v1
kind: Service
metadata:
  name: kasodds-metrics
  namespace: kasodds
  labels:
    app.kubernetes.io/name: kasodds
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kasodds
  ports:
    - name: metrics
      port: 9464
      targetPort: metrics
