apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kasodds
  namespace: kasodds
  labels:
    app.kubernetes.io/name: kasodds
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kasodds
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - kasodds
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
